name: optional_extensions
description: Dart package that wrap Optional to create extension methods
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  optional: ^6.1.0+1
  get: ^4.6.5
  flutter_spinkit: ^5.1.0

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0
