/// Flutter icons BlazeRetailPos
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BlazeRetailPos
///      fonts:
///       - asset: fonts/BlazeRetailPos.ttf
///
/// 
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
///
// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart';

class BlazeRetailPos {
  BlazeRetailPos._();

  static const _kFontFam = 'BlazeRetailPos';
  static const String? _kFontPkg = null;

  static const IconData transactions = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_id = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_keyboard = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bar_code = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cash_drawer = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exit = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scale = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scanner = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notes = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData print_1 = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData receipt = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData resume = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData review_checkmark = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData orders = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData start = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData members = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData claim = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter_icon = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cross_circle = IconData(0xe880, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
